:doctype: book

== Practical Exercise 1-6

This is the sixth of a series of PEs that will arm you with the skills to build components of what will become a complete program. By the end of the series, you will build a program that implements steganography; the art of hiding information.

---

Least Significant Bit (LSB) steganography is a technique to hide data by spreading the data's bits over multiple bytes within what's called the *cover*. The cover is typically an image whereby modifying single bits within the pixels results in slight color or intensity changes that are very hard to visually detect. This is done by placing the first bit of the data in the right-most (LSB) bit of the first byte of the cover. Then the second bit of the data is placed in the right-most (LSB) bit of the second byte of the cover. This is repeated until all of the data is spread across the bytes of the cover.

The aim of this PE is to build upon the previous PEs by writing a script that encrypts a message using a very simple caesar cipher. This cipher is a substitution cipher in which each letter in the plaintext is shifted a certain number of places up or down the alphabet.

.Example message that has been shifted by 1
----
defend the east wall of the castle
efgfoe uif fbtu xbmm pg uif dbtumf
----

---

==== [black]*Part 1 - Caesar*

* Begin a Python 3 REPL session and enter the code shown.

----
>>> chr(ord('a') + 1)
'b'
>>> chr(ord('b') - 1)
'a'
----

If the above were done across an entire string (excluding non-alpha characters), that would be an implementation of caesar cipher with key of 1... for a portion of the alphabet. Modulus can be used to wrap around values such that a 'z' would become an 'a' in the ciphertext.

----
>>> 0 % 26
0
>>> 1 % 26
1
>>> 25 % 26
25
>>> 26 % 26
0
>>> 27 % 26
1
----

So if the alphabet were numbered 0-25, all that would be needed is to modulus 26 the value after incrementing/decrementing by the value of the key. The alphabet is not numbered 0-25 when `ord()` and `chr()` are used. Those functions deal with ASCII codes, so lowercase letters are numbered 97-122. Just subtract 97 before the modulus and add 97 after.

----
>>> c = 'a'
>>> key = 1
>>> chr(((ord(c)+key-97)%26)+97)
'b'
>>> c = 'z'
>>> chr(((ord(c)+key-97)%26)+97)
'a'
----

---

==== [black]*Part2 - Translate*

Part 1 code could be used to implement the Caesar Cipher. However, the Python 3 standard library includes a couple of features that can be used to aid in accomplishing the same thing more clearly. `str` types have a member called `translate()`. This function returns a copy of the string in which each character has been mapped through the given translation table. The translation table argument to `translate()` is a dictionary that maps ordinals (ASCII values) to other ordinals or strings.

* Begin (or continue) a Python 3 REPL session. Enter the code shown below and observe the results.

----
>>> t = { ord('a'): 'zzz', ord('g'): None }
>>> s = 'abcdefg'
>>> s.translate(t)
'zzzbcdef'
----

The `a` has been replaced by the string `zzz` and the `g` has been removed. This mechanism can be used to implement the Caesar Cipher by explicitly specifying the translation from one character to another. Consider how this might look in code for a shift of 1 (it is not necessary to type this in).

----
t1 = { 
    ord('a'): 'b', 
    ord('b'): 'c',
    ord('c'): 'd'
}
----

Creating such a dictionary is alot of typing. Whether this is clearer than other methods is debatable at best, but it's certainly not concise. 

`str.maketrans()` returns a translation table usable for `str.translate()`. This method is _static_, meaning that, while it is a member of `str`, it need not have an object of type `str` to call. Its invokation is made by calling the method on a class/type rather than on an instance.

.Example of calling a static method of `str`
----
>>> transtable = str.maketrans(arg)
----

`maketrans()` is a versatile method that can take 1, 2, or 3 arguments. If given 2 arguments, they must be strings of equal length. The resulting dictionary will map each character in the first argument to the corresponding character in the second argument.

.Example of a translation table for Caesar Cipher with a shift of 1
----
>>> str.maketrans('abcdefghijklmnopqrstuvwxyz','bcdefghijklmnopqrstuvwxyza')
{97: 98, 98: 99, 99: 100, 100: 101, 101: 102, 102: 103, 103: 104, 104: 105, 105: 106, 106: 107, 107: 108, 108: 109, 109: 110, 110: 111, 111: 112, 112: 113, 113: 114, 114: 115, 115: 116, 116: 117, 117: 118, 118: 119, 119: 120, 120: 121, 121: 122, 122: 97}
----

This is only slightly more convenient than manually making a dictionary. It still suffers from the limitation of not being general for any key (shift). In the next part you'll learn about a data structure that can remedy this.

---

==== [black]*Part 3 - Deque*

In the `collections` module is `deque`. Pronounced "deck", this double-ended queue is a data structure which provides efficient inserts and deletes from both the head (front/start) and tail (back/end). As such, it is an ideal data structure for rotating elements within a collection. Enter the following code and observe the results:

----
>>> from collections import deque
>>> d = deque('abcdef')
>>> d
deque(['a', 'b', 'c', 'd', 'e', 'f'])
>>> d.rotate(1)
>>> d
deque(['f', 'a', 'b', 'c', 'd', 'e'])
----  

---

==== [black]*Part 4 - Deliverable*

Write a Python script that can encrypt and decrypt a message using the Caesar Cipher. Your script should implement the functions shown below. Run `python3 check.py` to check your work.

[TIP]
Use `deque`, `rotate()`, `maketrans()`, and `translate()` to implement the Caesar Cipher in only a few lines of code.

----
include::deliverable.py[]
----

---

*END*
